trigger_job_now:
  fields:
    job_id:
      required: true
      example: "01JABCDEF0123456789"
      selector:
        text:

refresh_spaces:

slot_freed:
  fields:
    space:
      example: "Court 1"
      selector:
        text:
    start:
      example: "2026-10-01T20:00:00"
      selector:
        text:
